# Generated by Django 5.0.6 on 2024-05-30 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("web", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userinfo",
            name="depart",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="web.department",
                verbose_name="部门",
            ),
        ),
        migrations.AlterField(
            model_name="userinfo",
            name="time",
            field=models.DateField(verbose_name="入职时间"),
        ),
    ]
